"""added content

Revision ID: 428e87d7aab3
Revises: 82ff1abc3173
Create Date: 2025-02-15 21:23:44.573988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428e87d7aab3'
down_revision: Union[str, None] = '82ff1abc3173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bookmarks', ['id'])
    op.add_column('comments', sa.Column('content', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'comments', ['id'])
    op.create_unique_constraint(None, 'properties', ['id'])
    op.create_unique_constraint(None, 'property_images', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'property_images', type_='unique')
    op.drop_constraint(None, 'properties', type_='unique')
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_column('comments', 'content')
    op.drop_constraint(None, 'bookmarks', type_='unique')
    # ### end Alembic commands ###
